name: orama_admin
description: "A new Flutter project."
publish_to: 'none'
version: 2.7.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1
  intl: ^0.19.0
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  mobx_codegen: ^2.6.1
  logging: ^1.2.0
  http: ^1.2.1
  dio: ^5.5.0+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.27.1
  syncfusion_flutter_pdfviewer: ^27.2.5
  open_filex: ^4.5.0
  syncfusion_flutter_pdf: ^27.2.4
  share_plus: ^10.1.2
  google_api_availability: ^5.0.0
  pdf: ^3.11.1
  excel: ^4.0.6
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.2
  cloud_functions: ^5.5.2
  internet_connection_checker: ^3.0.1
  collection: ^1.19.0
  app_installer: ^1.3.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

dependency_overrides:
  path_provider_android: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/images/
    - shorebird.yaml

   